server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: class-service
          uri: lb:http://CLASS-SERVICE
          predicates:
            - Path=/api/v1/class/**
        - id: salle-service
          uri: lb:http://CLASS-SERVICE
          predicates:
            - Path=/api/v1/salles/**
        - id: etudiant-service
          uri: lb:http://ETUDIANT-SERVICE
          predicates:
            - Path=/api/v1/etudiants/**
        - id: inscription-service
          uri: lb:http://ETUDIANT-SERVICE
          predicates:
            - Path=/api/v1/inscriptions/**
        - id: notification-service
          uri: lb:http://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**

