server:
  port: 8050
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5445/professeur
    username: linho
    password: linho
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "premiere migration"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
